spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "secret"
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop

  flyway:
    baseline-on-migrate: true
    schemas: public
    enabled: true
    locations: db/migration

server:
  error:
    include-message: always

