spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "secret"
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always

