name: Task Management CI Pipline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: build with gradle
        run: chmod +x ./gradlew

      - name: test with gradle
        run: ./gradlew build

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: task-management-service-artifact
          path: target/*.jar